AWSTemplateFormatVersion: '2010-09-09'
Description: My EC2 instance template file
Resources:
  MyEC2ViaCFT:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07d9b9ddc6cd8dd30
      InstanceType: t2.micro
      SecurityGroups: 
        - !Ref MySGCustom
      KeyName: TestKeyPair

  MySGCustom:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Custom Security Group for my EC2"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
